name: kursovaya
services:
  api-gateway:
    container_name: cinema_mastery_api-gateway
    build:
      context: server
      dockerfile: ./cmd/api-gateway/Dockerfile
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app

  film_service:
    container_name: cinema_mastery_film_service
    build:
      context: server
      dockerfile: ./cmd/film_service/Dockerfile
    ports:
      - ${FILM_SERVICE_PORT}:${FILM_SERVICE_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app

  cinema_service:
    container_name: cinema_mastery_cinema_service
    build:
      context: server
      dockerfile: ./cmd/cinema_service/Dockerfile
    ports:
      - ${CINEMA_SERVICE_PORT}:${CINEMA_SERVICE_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app

  minio:
    image: quay.io/minio/minio
    container_name: kursovaya_minio
    ports:
      - "127.0.0.1:10420:9000"
      - "127.0.0.1:10421:9001"
    volumes:
      - ./.data/minio:/data
    env_file:
      - .env
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - app

  postgres:
    image: postgres:16.8-alpine3.21
    container_name: kursovaya_postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - app

networks:
  app:
    driver: bridge