basePath: /
definitions:
  entities.Error:
    properties:
      error:
        type: string
    type: object
  entities.LoginUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  entities.LoginUserResponse:
    properties:
      role:
        type: string
      token:
        type: string
    type: object
info:
  contact: {}
  title: Kino API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Вход пользователя в систему с выдачей jwt и роли
      parameters:
      - description: Данные для входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entities.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная аутентификация
          schema:
            $ref: '#/definitions/entities.LoginUserResponse'
        "400":
          description: Некорректные данные для входа
          schema:
            $ref: '#/definitions/entities.Error'
        "500":
          description: Ошибка на стороне сервера
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Аутентификация пользователя
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
